{
    "custom-styles": {
        "Alerts": {
            "Alert Level 1": {
                "background-color": "#181818",
                "selected-text-color": "#cc8c3c",
                "text-color": "#cc8c3c"
            },
            "Alert Level 2": {
                "background-color": "#181818",
                "selected-text-color": "#cc8c3c",
                "text-color": "#cc8c3c"
            }
        },
        "CSV": {
            "Column 1": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 1 Separator": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 4": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            },
            "Column 4 Separator": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            },
            "Column 5": {
                "selected-text-color": "#cfcfc2",
                "text-color": "#cfcfc2"
            },
            "Column 5 Separator": {
                "selected-text-color": "#cfcfc2",
                "text-color": "#cfcfc2"
            },
            "Column 6": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 6 Separator": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 7": {
                "selected-text-color": "#f44f4f",
                "text-color": "#f44f4f"
            },
            "Column 7 Separator": {
                "selected-text-color": "#f44f4f",
                "text-color": "#f44f4f"
            },
            "Column 8": {
                "selected-text-color": "#75bfc4",
                "text-color": "#609ca0"
            },
            "Column 8 Separator": {
                "selected-text-color": "#75bfc4",
                "text-color": "#609ca0"
            },
            "Column 9": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            },
            "Column 9 Separator": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            }
        },
        "CSV (pipe)": {
            "Column 1": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 1 Separator": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 4": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            },
            "Column 4 Separator": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            },
            "Column 5": {
                "selected-text-color": "#cfcfc2",
                "text-color": "#cfcfc2"
            },
            "Column 5 Separator": {
                "selected-text-color": "#cfcfc2",
                "text-color": "#cfcfc2"
            },
            "Column 6": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 6 Separator": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 7": {
                "selected-text-color": "#f44f4f",
                "text-color": "#f44f4f"
            },
            "Column 7 Separator": {
                "selected-text-color": "#f44f4f",
                "text-color": "#f44f4f"
            },
            "Column 8": {
                "selected-text-color": "#75bfc4",
                "text-color": "#609ca0"
            },
            "Column 8 Separator": {
                "selected-text-color": "#75bfc4",
                "text-color": "#609ca0"
            },
            "Column 9": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            },
            "Column 9 Separator": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            }
        },
        "CSV (semicolon)": {
            "Column 1": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 1 Separator": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 4": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            },
            "Column 4 Separator": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            },
            "Column 5": {
                "selected-text-color": "#cfcfc2",
                "text-color": "#cfcfc2"
            },
            "Column 5 Separator": {
                "selected-text-color": "#cfcfc2",
                "text-color": "#cfcfc2"
            },
            "Column 6": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 6 Separator": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 7": {
                "selected-text-color": "#f44f4f",
                "text-color": "#f44f4f"
            },
            "Column 7 Separator": {
                "selected-text-color": "#f44f4f",
                "text-color": "#f44f4f"
            },
            "Column 8": {
                "selected-text-color": "#75bfc4",
                "text-color": "#609ca0"
            },
            "Column 8 Separator": {
                "selected-text-color": "#75bfc4",
                "text-color": "#609ca0"
            },
            "Column 9": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            },
            "Column 9 Separator": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            }
        },
        "CSV (whitespace)": {
            "Column 1": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 1 Separator": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 4": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            },
            "Column 4 Separator": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            },
            "Column 5": {
                "selected-text-color": "#cfcfc2",
                "text-color": "#cfcfc2"
            },
            "Column 5 Separator": {
                "selected-text-color": "#cfcfc2",
                "text-color": "#cfcfc2"
            },
            "Column 6": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 6 Separator": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 7": {
                "selected-text-color": "#f44f4f",
                "text-color": "#f44f4f"
            },
            "Column 7 Separator": {
                "selected-text-color": "#f44f4f",
                "text-color": "#f44f4f"
            },
            "Column 8": {
                "selected-text-color": "#75bfc4",
                "text-color": "#609ca0"
            },
            "Column 8 Separator": {
                "selected-text-color": "#75bfc4",
                "text-color": "#609ca0"
            },
            "Column 9": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            },
            "Column 9 Separator": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            }
        },
        "Doxygen": {
            "Attention": {
                "bold": false
            },
            "Entities": {
                "bold": false
            },
            "HTML Tag": {
                "bold": false
            },
            "Note": {
                "bold": false
            },
            "Tags": {
                "bold": false
            },
            "Todo": {
                "bold": false
            },
            "Warning": {
                "bold": false
            },
            "Word": {
                "bold": false
            }
        },
        "JSON": {
            "Style_Seperator_Array": {
                "selected-text-color": "#cfcfc2",
                "text-color": "#cfcfc2"
            },
            "Style_Seperator_Pair": {
                "bold": false
            }
        },
        "Python": {
            "Decorator": {
                "selected-text-color": "#cfcfc2",
                "text-color": "#cfcfc2"
            },
            "F-String": {
                "selected-text-color": "#73c936",
                "text-color": "#73c936"
            },
            "F-String Deliminator": {
                "selected-text-color": "#73c936",
                "text-color": "#73c936"
            },
            "Import": {
                "selected-text-color": "#ffdd33",
                "text-color": "#ffdd33"
            }
        },
        "TSV": {
            "Column 1": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 1 Separator": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 4": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            },
            "Column 4 Separator": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            },
            "Column 5": {
                "selected-text-color": "#cfcfc2",
                "text-color": "#cfcfc2"
            },
            "Column 5 Separator": {
                "selected-text-color": "#cfcfc2",
                "text-color": "#cfcfc2"
            },
            "Column 6": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 6 Separator": {
                "selected-text-color": "#3daee9",
                "text-color": "#3daee9"
            },
            "Column 7": {
                "selected-text-color": "#f44f4f",
                "text-color": "#f44f4f"
            },
            "Column 7 Separator": {
                "selected-text-color": "#f44f4f",
                "text-color": "#f44f4f"
            },
            "Column 8": {
                "selected-text-color": "#75bfc4",
                "text-color": "#609ca0"
            },
            "Column 8 Separator": {
                "selected-text-color": "#75bfc4",
                "text-color": "#609ca0"
            },
            "Column 9": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            },
            "Column 9 Separator": {
                "selected-text-color": "#af81ff",
                "text-color": "#8e44ad"
            }
        }
    },
    "editor-colors": {
        "BackgroundColor": "#181818",
        "BracketMatching": "#96a6c8",
        "CodeFolding": "#224e65",
        "CurrentLine": "#282828",
        "CurrentLineNumber": "#ffdd33",
        "IconBorder": "#181818",
        "IndentationLine": "#3a3f44",
        "LineNumbers": "#52494e",
        "MarkBookmark": "#0404bf",
        "MarkBreakpointActive": "#8b0607",
        "MarkBreakpointDisabled": "#820683",
        "MarkBreakpointReached": "#6d6e07",
        "MarkError": "#da4453",
        "MarkExecution": "#4d4e50",
        "MarkWarning": "#f67400",
        "ModifiedLines": "#c04900",
        "ReplaceHighlight": "#808021",
        "SavedLines": "#1c8042",
        "SearchHighlight": "#414857",
        "Separator": "#333639",
        "SpellChecking": "#c0392b",
        "TabMarker": "#4d4d4d",
        "TemplateBackground": "#31363b",
        "TemplateFocusedPlaceholder": "#123723",
        "TemplatePlaceholder": "#123723",
        "TemplateReadOnlyPlaceholder": "#4d1f24",
        "TextSelection": "#484848",
        "WordWrapMarker": "#3a3f44"
    },
    "metadata": {
        "name": "gruber",
        "revision": 1
    },
    "text-styles": {
        "Alert": {
            "selected-text-color": "#95da4c",
            "text-color": "#95da4c"
        },
        "Annotation": {
            "selected-text-color": "#cc8c3c",
            "text-color": "#cc8c3c"
        },
        "Attribute": {
            "selected-text-color": "#ffdd33",
            "text-color": "#ffdd33"
        },
        "BaseN": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#cfcfc2"
        },
        "BuiltIn": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#cfcfc2"
        },
        "Char": {
            "selected-text-color": "#73c936",
            "text-color": "#73c936"
        },
        "Comment": {
            "selected-text-color": "#cc8c3c",
            "text-color": "#cc8c3c"
        },
        "CommentVar": {
            "selected-text-color": "#cc8c3c",
            "text-color": "#cc8c3c"
        },
        "Constant": {
            "selected-text-color": "#95a99f",
            "text-color": "#95a99f"
        },
        "ControlFlow": {
            "selected-text-color": "#ffdd33",
            "text-color": "#ffdd33"
        },
        "DataType": {
            "selected-text-color": "#95a99f",
            "text-color": "#95a99f"
        },
        "DecVal": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#cfcfc2"
        },
        "Documentation": {
            "selected-text-color": "#da4453",
            "text-color": "#a43340"
        },
        "Error": {
            "selected-text-color": "#da4453",
            "text-color": "#da4453",
            "underline": true
        },
        "Extension": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#cfcfc2"
        },
        "Float": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#cfcfc2"
        },
        "Function": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#cfcfc2"
        },
        "Import": {
            "selected-text-color": "#73c936",
            "text-color": "#73c936"
        },
        "Information": {
            "selected-text-color": "#e46700",
            "text-color": "#c45b00"
        },
        "Keyword": {
            "selected-text-color": "#ffdd33",
            "text-color": "#ffdd33"
        },
        "Normal": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#cfcfc2"
        },
        "Operator": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#cfcfc2"
        },
        "Others": {
            "selected-text-color": "#27ae60",
            "text-color": "#27ae60"
        },
        "Preprocessor": {
            "selected-text-color": "#95a99f",
            "text-color": "#95a99f"
        },
        "RegionMarker": {
            "selected-text-color": "#cc8c3c",
            "text-color": "#cc8c3c"
        },
        "SpecialChar": {
            "selected-text-color": "#cfcfc2",
            "text-color": "#cfcfc2"
        },
        "SpecialString": {
            "selected-text-color": "#da4453",
            "text-color": "#da4453"
        },
        "String": {
            "selected-text-color": "#73c936",
            "text-color": "#73c936"
        },
        "Variable": {
            "selected-text-color": "#95a99f",
            "text-color": "#95a99f"
        },
        "VerbatimString": {
            "selected-text-color": "#da4453",
            "text-color": "#da4453"
        },
        "Warning": {
            "selected-text-color": "#da4453",
            "text-color": "#da4453"
        }
    }
}
